### ISSUE TITLE
"Shared Props by Pose" fails with 2.2

### ISSUE THREAD

**Issue by rbruhn** [AVsitter/AVsitter#4] opened 2017-08-04 03:58 UTC
I assume this is the place to post questions about issues now?

I was updating some furniture with the new scripts and using the POSE script to rez an object for multiple poses. It doesn't seem to work anymore. Was there a change?

**Comment by mifi3000** [comment] 2017-08-04 05:36
Hi, There isn't a place yet for general usage questions, aside from those mentioned at https://avsitter.github.io/support.html. Your best bet for hands-on help would be the in-world group.

I don't believe anything has changed in the scripts since the last closed source version.

If you're looking for the example scripts for AVprop they were moved to https://avsitter.github.io/avsitter2_lsl_examples_avprop.html.

**Comment by Sei-Lisa** [comment] 2017-08-04 05:42
Hello, can you please be more specific on which script you mean, what it should do and what is not doing anymore?

I have been trying the `[AV]prop example #01` and found an issue that when you stand up, the prop doesn't derez. I'm looking into it. Is that what you mean?

**Comment by rbruhn** [comment] 2017-08-04 12:19
Thank you.

I'm speaking about the POSE.lsl script that allowed for reusing a prop in multiple poses. An example is below.

POSE.lsl
```
list SITTER_PROPS_N_POSES = [
    0, "CupProp", "Relax,Read,Chat,Breakfast"
]
```

AVpos
```
PROP1 CupProp|Black Cup|G1|<0.11697, 0.00271, 0.05693>|<0.00000, 19.00000, 0.00000>|right hand
```

**Comment by Sei-Lisa** [comment] 2017-08-04 15:28
Hm, I think you mean [Shared Props by Pose](https://avsitter.github.io/avsitter2_lsl_example_shared_props_by_pose.html). If so, It's working for me. What does it not do?

Remember that if you want a shared prop, you need to use `PROP3`, not `PROP1`.

**Comment by rbruhn** [comment] 2017-08-04 17:00
Yes, that is the script I'm using. However, as the instructions say at the top of the script:

"Props for a specific sitter can use PROP, PROP1 or PROP2."

Basically, I've used POSE.lsl before so the same prop can be used for more than one animation. Alleviating the need to create a prop line in AVpos for each animation were the same prop is used. You can see in my example above the prop is only for SITTER 0. For whatever reason, it's not working for me now. The object has the [AV]object script inside it. I'm using [AV]prop in the root prim. The object has correct permissions.

I created a single line prop for the Relax button animation to test whether the cup can be given to the user and it works:
```
PROP1 Relax|Black Cup|G1|<0.11697, 0.00271, 0.05693>|<0.00000, 19.00000, 0.00000>|right hand
```

I took another project I worked on and replaced all the old versions of AVSitter with the new open source
POSE:
```
PROP1 CuffsProp|Cuffs LA|G3|<0.448135, 0.000000, 0.093872>|<0.000000, 0.000000, 0.000000>|left lower arm
PROP1 CuffsProp|Cuffs RA|G3|<0.448135, 0.000000, 0.093872>|<0.000000, 0.000000, 0.000000>|right lower arm
PROP1 CuffsProp|Cuffs LL|G3|<0.448135, 0.000000, 0.093872>|<0.000000, 0.000000, 0.000000>|left lower leg
PROP1 CuffsProp|Cuffs RL|G3|<0.448135, 0.000000, 0.093872>|<0.000000, 0.000000, 0.000000>|right lower leg
```
AVpos
```
0, "CuffsProp", "Toe tease,Feathered,Edged,Slow milk,Necktie,Downtown,Hot lix,Slow blow,69 time,Lewd lotus,Hard hammer,Lovin' it,Ridin' gal,Open invite,Deep pump,Take her ass,Deep ass,Bend'n'peg,Hangin' peg,Cane him,Whip him"
```
 I didn't change the old [AV]object script in the cuffs though. It worked fine with the new open source scripts. I did try the cup with the old [AV]object script and it still didn't work. That's obviously not the problem.

Sooooooo.... I have no idea where things are going wrong with my current project. I'm just going to give up and use a separate line in the AVpos for each animation that uses the cup.
Thanks

**Comment by Sei-Lisa** [comment] 2017-08-04 17:58
Thanks for your description. It still may be a problem recently introduced, but it's hard to tell given that other instances work for you, and my own testing setup worked for me, so I couldn't reproduce it. Perhaps it's best to close this issue, keeping it in mind in case more people run into issues like that and can chime in.

**Closed by Sei-Lisa** 2017-08-04 17:58 UTC
