### ISSUE TITLE
RLV Cage released captive 

### ISSUE THREAD

**Issue by AlexaFinch** [AVsitter/AVsitter#142] opened 2021-10-02 02:14 UTC
There is an issue with creating RLV cages using AVsitter. When a "prisoner" logs out another person can access the menu and put someone else in the cage, thus releasing the first prisoner. This is not typical cage behavior in SL. 

The way this should work is if there is a prisoner in a cage either no one can get a menu except the key holder or if they do get a menu it only shows the settings and timer but does not allow anyone but the key holder to make changes. 

I am requesting that AVsitter RLV be changed to meet the correct cage behavior. 

Thanks
Alexa

**Comment by codeviolet** [comment] 2021-10-17 04:20
Thanks for communicating about your issue with me inworld and for making this request on Github.

With RECAPTURE 1 you should be seeing the avatar recaptured if they re-log (I checked that is working for me but if that is not happening for you it should be filed as a separate issue). However in regard to your issue as described above, I believe there is currently nothing stopping someone from jumping on the furniture or using the furniture's menu if the avatar who was captured has gone offline (and if someone gets on the furniture then it would no longer attempt to recapture if the previous captive logs back in). This is by design however if the current operation is stable I would hope the function could be improved to match your expectations at some point.

For instance, there could be a new AVcontrol feature (possible notecard option to enable) where IF the controlling avatar has set the Timelock feature then the furniture would eject any new sitters and refuse to give the menu to another avatar until the time had expired. I expect that then there would also need to be default limits placed on the Timelock duration as being able to lock furniture indefinitely from use may go against others expectations.

Further thoughts welcomed on how it would work. Hopefully someone who is coding for the project can look at it in future.

**Comment by AlexaFinch** [comment] 2021-10-17 04:46
Currently I have my cages set on RECAPTURE1. I'll have to test to see exactly what they are doing. I'm in the process of rebuilding part of my sim so will probably be a week or so before I can test them.

The issue  of someone else being able to jump in the cage while the previous prisoner is offline is a major issue. I can't in good conscious sell a cage with this behavior. Actually for a cage, the capture option should not be available when someone is locked in already. If anyone needs to see how a cage should be configured I have a cage room you can visit. Contact me for more info whether about the cage or about visiting.

**Comment by codeviolet** [comment] 2021-10-19 00:46
Thanks for the additional feedback. The idea of keeping furniture locked indefinitely while captive avatars are offline was discussed during the initial design of the AVcontrol plugin and it was felt that if furniture was abandoned by avatars going offline then it wasn't necessary to prevent new avatars from using it and it raises additional issues such as 1) whether or not to pause the timelock countdown while avatars were offline, 2) how long it would wait for avatars to reappear before giving up 3) and what kind of access list was required to allow avatars to bypass the behavior. I don't know then answers to any of those but I know it makes the code complex.

That said, if you consider it major then I hope someone with the relevant time and experience will look at it. The code is all opensource in the event that you prefer to have new features added before waiting for someone to code them. Appreciate your understanding and any further feedback on the issue.

**Comment by AlexaFinch** [comment] 2021-11-09 01:53
Sei-Lisa said, "AVsitter is not a cage engine, just like it's not a vehicle engine"

This needs to be made clear on the Second Life Market Place ad where I paid L$3,000 for the scripts. But I would ask why is RLV plug-ins included if not to make a cage. And it you reply "toys." Well, I would expect toys to be lockable like a cage is. So it seems to me regardless of your argument, the scripts are flawed. This explains why some of the toys I have misbehave similarly to my complaint about using AVsitter for cage scripts. 

I've bought a few cells on MP that use the AVsitter scripts. They all exhibit the same behavior. Since discovering the flaw I've removed the cells from my cage room. The sad thing is makers don't usually tell you they used AVsitter to build the cage. That makes it difficult to avoid buying things that use the scripts.

**Comment by codeviolet** [comment] 2021-11-09 04:29
Thanks for your additional feedback @AlexaFinch, it's good to have your opinion on the importance of the ability to keep a lock RLV furniture while avatars are offline.

As far as I can see, AVsitter's Marketplace listing does not specifically mention RLV, so I don't see anything misleading there in relation to the RLV plugin. As is indicated on the Marketplace: since the scripts became open-source a primary purpose of the Marketplace listing is to provide a means by which users can support the project's development. In keeping with this, if you are unsatisfied then you are welcome to contact me in-world to request a return to you of the amount received (I would be happy to oblige and you can continue to use the scripts regardless - after all, they are open-source scripts).

The question of whether the RLV plugin should support the additional lock feature discussed remains up to the current script developers (or anyone else with inclination/time to work on it), so I will have to leave it to their best judgement. While the feature was not seen as vital or even suggested by anyone when the plugin was being made it doesn't seem unreasonable to me for you to want the offline lock as an option - I don't think we've given anyone reason to expect the feature though.

I'd prefer you be comfortable using furniture people have made with AVsitter so I hope that if the feature is not to be added to Avsitter's RLV plugin then someone might develop a third party plugin script with the capabilities you need.

**Comment by AlexaFinch** [comment] 2021-11-09 23:10
I have a friend who is looking into the possibility of creating a plugin that would solve my issue with the  current scripts. Time to dedicate to the project is the issue. 

Hopefully she's successful so I can deploy the cages I removed.

**Comment by codeviolet** [comment] 2021-11-10 04:29
Thanks to all for the feedback on this issue. Closing this issue now, please re-open if there is a future need.

**Closed by codeviolet** 2021-11-10 04:29 UTC
