### ISSUE TITLE
[AV]sitA 1650, 19 - Dead Code, SL - Alchemy

### ISSUE THREAD

**Issue by ChefRude** [AVsitter/AVsitter#105] opened 2018-09-17 17:26 UTC
I have just downloaded the latest SL version of AvSitter, and was able to copy/paste/compile every other script except [AV]sitA.

It provides me these errors:
(1650,19) WARNING: Dead code found beyond return statement

`    return;
    @J_autoGen00002;`
This is the code it pinpoints to.

There is a lot of nuls and function arg calls, and then

(0, 0) ERROR Byte code assembly failed - out of memory

Running Second Life on Alchemy vs 33 (latest, 64x)

Thanks

**Comment by Sei-Lisa** [comment] 2018-09-17 20:27
Hello, ChefRude, thanks for your report.

Warnings are not fatal to the compilation, and that warning is bogus anyway, because the code isn't dead. Anyway, the error that is stopping the compilation is the out of memory error; you wouldn't even see the warning if it wasn't because of the error.

That, together with the lot of nuls and function arg calls, indicates that you're NOT compiling [AV]sitA (and possibly every other script) in Mono mode. That is not supported, and it's very likely that the other scripts won't work properly. Only Mono is supported.

In order to fix that, you need to drop all scripts into a prim with the CTRL key held, open each script, check the Mono checkbox, save it and wait for the "Compile successful / Save complete" message, then close it and repeat the process until they are all saved in Mono. Then take them all back and use these instead of the ones in your inventory.

Also, it would be nice if you told the Alchemy viewer developers to compile scripts to Mono by default when saving them in inventory. Firestorm is doing that already.

The next version will hopefully include a more complete [Import Guide](https://github.com/Sei-Lisa/AVsitter/blob/sei-force-mono-compile/AVsitter2/IMPORT_GUIDE.md) and will not allow compilation unless saving in Mono.

**Comment by ChefRude** [comment] 2018-09-17 22:27
Ok ill try again. I decided to buy it in the Marketplace just to support you guys anyway and that version worked ;) thanks so much.

**Comment by Sei-Lisa** [comment] 2018-09-17 23:10
Thank you very much, that's very appreciated!

**Comment by ChefRude** [comment] 2018-09-18 19:39
Oh I noticed a new weird bug.

Using the MP version of AvSitter, when I adjust poses, and dump them, it only spits out the Sitter 0 poses.
I have had to go back and manually do all the AvPos notecard editing and pasting from "as you save" dumps for other sitters bc they just don't populate.

Am I doing something wrong? Or should I make a new ticket?

**Comment by Sei-Lisa** [comment] 2018-09-19 12:05
I've just tried with a simple setup and it worked for me, therefore there may be other problems related to your setup.

Please open a new issue indicating whether there were many poses, whether you received any script error during your setup (like the infamous "stack/heap collision"), and if possible, the steps necessary to reproduce the problem. The latter would be a big help, because it would enable us to investigate why it's not working as expected.

**Closed by Sei-Lisa** 2018-09-19 12:05 UTC
Labels: Not an AVsitter bug
