### ISSUE TITLE
DUMP - only Sitter 0 info dumped

### ISSUE THREAD

**Issue by ChefRude** [AVsitter/AVsitter#106] opened 2018-09-19 17:28 UTC
These are the details:

Using a mesh object as the root/container.
Object contains ~400 animations.
Sitter 0/1 each have about 200 animations each.
Sitter 2 has about 30 animations.
All animations types are SYNC.
Hosts 3 seaters.
70% are 2 seater 0/1 syncs, a the rest are 3 seater 0/1/2 syncs.
See "ObjectContentScreenshot.png" to see the AVSitter Scripts I've added to the object.

Original MENU structure was very complex, and several sublevels deep, across many of the first level menus.

See attached "OriginalMenuAttempt.txt" for example. I removed all poses beneath the menus, and made the names letters and numbers to display depth. 

Was a conversion from an MLP. Unaware there was a plugin for that, I did it manually. I was not aware at the time you required individual {sit}<params> for each sitter at the end of each sitters area (this was not made clear in the WIKI I was following, as they show "all simple poses with pose rot/pos at the bottom, or menu structures" but nothing complex enough to rival the engine I was building, so I had placed them at the bottom of the AVPos card, as a list, as I was used to in MLP and poseball type sit scripts.
SITTER0
SITTER1
SITTER2
then 
{pose}<sitter0pos><sitter0rot><sitter1pos><sitter1rot><sitter2pos><sitter2rot> etc. for every single pose

This of course did not work, so all of my poses were defaulted to 0,0,0 0,0,0 and the script did not read them at all. After several hours adjusting poses from scratch, I did a dump. See FirstDump.txt for that.

So after 2 days, I found out about the MLP convertor. I added this to my old engines (2), and started the process. It did it correctly, and I then copy/pasted these into a single AvPos Notecard. I decided, since it took 5 minutes to read the card at all, because it was so long, to simplify the menu. I got it down to first level menus most of the time, and 1 menu with submenus.
See "SecondAttempt.txt" for that, as before, with a stripped structure for simplicity.

As before, I adjusted, since the root prim for all of my engines and my current engine are all at different rotations in world, I still needed a lot of adjusting. And I didnt try to "fix" them in the MLP system before importing to the new mesh object.

The latest dump (just did it) using that menu structure can be found at "latestdump.txt". It still ends with Sitter 0. I tried swapping between users, assuming maybe I needed to dump with each invidividual one, to get its dump... but that still only gave me Sitter 0 data.

I have received no script errors, stack/heap collissions or anything else that shows me "something went wrong".

If you need any other info, please let me know.

[OriginalMenuAttempt.txt](https://github.com/AVsitter/AVsitter/files/2398083/OriginalMenuAttempt.txt)
[firstdump.txt](https://github.com/AVsitter/AVsitter/files/2398084/firstdump.txt)
[SecondAttempt.txt](https://github.com/AVsitter/AVsitter/files/2398085/SecondAttempt.txt)
[latestdump.txt](https://github.com/AVsitter/AVsitter/files/2398086/latestdump.txt)
![objectcontentscreeshot](https://user-images.githubusercontent.com/19828854/45770259-de01ee80-bc0f-11e8-9e06-764a4e1a7964.png)

**Comment by Sei-Lisa** [comment] 2018-09-21 14:52
Thanks for the detailed report, and sorry it took a bit for me to find some time to investigate this issue. Unfortunately I still can't reproduce it.

Note that [AV]root and [AV]root-security are mutually exclusive. You only need one of them, please see https://avsitter.github.io/avsitter2_utilities.html#avroot-script and the next section for details on when these are necessary. Anyway, the problem is obviously not related to that.

I don't have a setup with so many poses, so what I did was to take **AVsitter Example#11a (couples/3some)** from the Examples box, remove [AV]select, and add [AV]prop, [AV]root, [AV]root-security, [AV]adjuster and [AV]helper. Then I sat on it, clicked [ADJUST], then [HELPER] and then [DUMP]. The dump worked and showed all three sitters.

Given the number of poses, I still suspect it's likely to be a memory overflow, which for some reason you can't see.

One question. The dump always ends with an empty line, then a line that says 'COPY ABOVE INTO "AVpos" NOTECARD', then another empty line, and then a link. Did you get these?

**Comment by ChefRude** [comment] 2018-09-21 15:43
Ah ok... let me remove the root-script since I was not aware they were competing.

It is very possible its "too many poses" I think I remember, but cannot re-find, the "this is limited to 300 animations" snippet.... Could not find it in the wiki/guide page anyway. Is there such a known limit? Or am I just crazy? After days of trying to make this thing work (not at all your fault) I might very well be loco.

Doing another dump now, let me see if I get the "copy above" line. I can't remember if I cut it or not... 
Nope... it doesn't give me the "COPY ABOVE INTO AVPos" line. It just ENDS at the last posrot line.

Yeah this is looking like memory overload.... Still 0 errors though :laughing: 

An option would be to cut off the 3 person poses and put them in another piece of the furniture right? so if they want to access that second set of poses they can sit on a different prim, no? (Doing so would trim about 80 animations from the notecard and object... still not 300 but maybe it won't overload?)

**Comment by ChefRude** [comment] 2018-09-21 17:07
I removed the 3 sitter syncs and placed them in a separate item with 3 prim pieces linked together. I then re did the 2 person item (still over 300 anims) and dumped. It still ended with the sitter 0 dump, and without the "copy above" line :D

**Comment by Sei-Lisa** [comment] 2018-09-21 18:15
There's no exact limit on the number of poses. Every letter or space or symbol in the menu uses memory, as does every animation name. Scripts have the total memory limited to what is said in chat in the beginning.

I have no idea what is causing the dump to fail. Could you please ensure that **[AV]sitA 1** and **[AV]sitB 1** are both running? Open them and check that the Running checkbox is ticked.

**Comment by ChefRude** [comment] 2018-09-22 20:14
Ok... yep

They are both on and running...
![mono running](https://user-images.githubusercontent.com/19828854/45921385-9040ec80-be82-11e8-8e95-9e2913ee23ec.png)

**Comment by ChefRude** [comment] 2018-09-22 20:14
if I shortened pose/anim names would that maybe help?

**Comment by Sei-Lisa** [comment] 2018-09-22 22:33
I don't know. I have no idea of what's causing this issue and I can't investigate it.

Do you think you could send me your actual AVpos notecard inworld? Perhaps that suffices to reproduce the problem. (SL avatar name: Sei Lisa, display name: Sei Shōnagon)

**Comment by ChefRude** [comment] 2018-09-24 19:32
Heh, ok sorry for delay, was fixing up the positions and weeding out bad poses etc. to see if that helped. I'll shoot over the AvPos in a sec once I throw it on the bed and try another dump for giggles.

**Comment by ChefRude** [comment] 2018-09-24 19:46
Ok, update.
I removed... like 20 syncs or so, and ran a dump.
And it got MOST of the way through Sitter 1. which is news, but it did not give me the "end of the copy/paste" line.

And no errors yet. But Im thinking its a memory overload of some kind.

**Comment by ChefRude** [comment] 2018-09-24 21:44
Ok, with Sei-Lisa's suggestion, we reset the object, and it dumped correctly :) This has been solved for now. If I see it occur again I will create another ticket. Thank you so much.

**Comment by Sei-Lisa** [comment] 2018-09-24 22:09
Thanks for your detailed report though, and for providing the notecard for investigation. Since there was no way to reproduce the issue, all that can be done for now is close it. Please let us know in case you happen to run into the same issue in a way that can be replicated.

**Closed by Sei-Lisa** 2018-09-24 22:09 UTC
Labels: Unconfirmed, bug

**Comment by jmfergeau** [comment] 2022-05-12 10:20
Sorry for necropost but i'm running into the same issue.
Resetting the scripts doesn't do anything.

I found the source of my problem tho. the [AV]prop script. If it doesn't run, it will block the dump. So the answer is either set the prop script to run, or remove the script.

(also hurray to sl to not set all the scripts to running when i click "set all scripts to running" :D )
